### ISSUE TITLE
Tracking issue for version 5

### ISSUE THREAD

**Issue by mscuthbert** [cuthbertLab/music21#235]
- [ ] Integrate and document tree directory
- [ ] Finish up analysis/reduceChords using trees
- [ ] SMuFL support
- [ ] Integrate Style objects with Groups
- [ ] MusicXML v. 3. support
- [ ] Percussion!
- [ ] Tablature

**Comment by bzier** [comment]
Hi @mscuthbert, I am working with music21 for the first time and found some limitations. Specifically, I am working with midi files for guitar tabs I have converted from guitar pro files.

The first thing I found was that there were missing instrument definitions for many of the General MIDI guitar instruments. I was able to easily add these (will send a PR relatively soon - need to document & test).

The second is that percussion tracks (channel 10) are not currently supported, which led me to this issue. I am wondering if work has started on this, and/or if there is a design/plan around implementing this support. I'm interested in pursuing it, but don't want to head off in my own direction if you already have thoughts for how to approach it. Would it make sense to open an issue specifically for the percussion checklist item to continue this discussion?

Thanks,
-Brian

**Comment by mscuthbert** [comment]
Hi Brian -- can we move this to another issue, since this issue is for the main tracking for things to do, and we can reference that issue there.  Not every General MIDI patch will get its own instrument (GuitarFretNoise for instance, never; Bright Grand Piano won't get one separate from Piano) but I'm sure that we could do more w/ some guitars.  Please make an issue for that and a separate one for percussion and we can discuss there.

**Comment by mscuthbert** [comment]
remaining issues moved to v10
